### ISSUE TITLE
Setting up Commitlint + Rules

### ISSUE THREAD

**Issue by coreyja** [BattlesnakeOfficial/docs-new#4]
Quoting Bultz from Discord who summed up this nicely. This is from the `#wiki-working-group` in the [Battlesnake Discord](https://discord.gg/gPYEZEQUyp)

> So for commits, are there a general consensus of:
> - type and scope = error 
> - rest = warning
> 
> type and scope are in the conventional commits, so if they use that, doesn't really look like it's someone first time. So I would say it's fair. 
> 
> Not sure if the only thing to say we enforce is the max 50 char in the subject and warning on the rest or make the subject also a warning. 
> 
> it looks like we can change the warning and error messages, so we can make it more clear on the WHY, instead of "this is a warning", "this is a error"

Links:
https://github.com/conventional-changelog/commitlint

**Comment by DaBultz** [comment]
Just gonna let people know, I'm working on this one.
